/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuroraButton: typeof import('./src/components/ui/AuroraButton.vue')['default']
    ChatIntegration: typeof import('./src/components/report/ChatIntegration.vue')['default']
    ChatMessage: typeof import('./src/components/chat/ChatMessage.vue')['default']
    CreateChallengeForm: typeof import('./src/components/family/CreateChallengeForm.vue')['default']
    GlobalHeader: typeof import('./src/components/GlobalHeader.vue')['default']
    GoalCard: typeof import('./src/components/health/GoalCard.vue')['default']
    HealthBarChart: typeof import('./src/components/charts/HealthBarChart.vue')['default']
    HealthCard: typeof import('./src/components/health/HealthCard.vue')['default']
    HealthHeatmap: typeof import('./src/components/charts/HealthHeatmap.vue')['default']
    HealthLineChart: typeof import('./src/components/charts/HealthLineChart.vue')['default']
    HealthRadarChart: typeof import('./src/components/charts/HealthRadarChart.vue')['default']
    Input: typeof import('./src/components/ui/Input.vue')['default']
    InsightCard: typeof import('./src/components/report/InsightCard.vue')['default']
    LoadingIndicator: typeof import('./src/components/ui/LoadingIndicator.vue')['default']
    MCPErrorHandler: typeof import('./src/components/error/MCPErrorHandler.vue')['default']
    MCPStatusIndicator: typeof import('./src/components/ui/MCPStatusIndicator.vue')['default']
    MemberManagement: typeof import('./src/components/family/MemberManagement.vue')['default']
    MemberSwitcher: typeof import('./src/components/family/MemberSwitcher.vue')['default']
    Modal: typeof import('./src/components/ui/Modal.vue')['default']
    OptimizedChart: typeof import('./src/components/charts/OptimizedChart.vue')['default']
    PlanCard: typeof import('./src/components/health/PlanCard.vue')['default']
    PulsingDot: typeof import('./src/components/ui/PulsingDot.vue')['default']
    ReportChatModal: typeof import('./src/components/report/ReportChatModal.vue')['default']
    ReportSummary: typeof import('./src/components/report/ReportSummary.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/ui/Select.vue')['default']
    SkeletonLoader: typeof import('./src/components/common/SkeletonLoader.vue')['default']
    TheToaster: typeof import('./src/components/ui/TheToaster.vue')['default']
    Toast: typeof import('./src/components/ui/Toast.vue')['default']
    TypingIndicator: typeof import('./src/components/chat/TypingIndicator.vue')['default']
    UserPersonalizationPanel: typeof import('./src/components/personalization/UserPersonalizationPanel.vue')['default']
    VirtualReportList: typeof import('./src/components/report/VirtualReportList.vue')['default']
  }
}
