"""
AuraWell Health Orchestrator v2

The core orchestration engine that coordinates health data analysis,
AI-powered insights generation, and personalized health plan creation.
"""

import logging
from datetime import datetime, timezone, timedelta
from typing import Dict, List, Optional, Any
from dataclasses import dataclass

from ..models.enums import InsightType, InsightPriority

logger = logging.getLogger(__name__)

# Import the unified HealthPlan model from API models
try:
    from ..models import HealthPlan, HealthPlanModule
except ImportError:
    # Fallback for development/testing
    logger.warning("Could not import HealthPlan from models, using local definition")

    @dataclass
    class HealthPlan:
        """Fallback HealthPlan definition for compatibility"""

        plan_id: str
        title: str
        description: str
        modules: List[Dict[str, Any]]
        duration_days: int
        status: str = "active"
        progress: float = 0.0
        created_at: datetime = None
        updated_at: datetime = None


@dataclass
class HealthInsight:
    """Represents a health insight generated by AI analysis"""

    insight_id: str
    insight_type: InsightType
    priority: InsightPriority
    title: str
    description: str
    recommendations: List[str]
    data_points: Dict[str, Any]
    confidence_score: float  # 0.0 to 1.0
    generated_at: datetime
    expires_at: Optional[datetime] = None


@dataclass
class ComprehensiveHealthReport:
    """Complete health analysis report with insights and recommendations"""
    
    user_id: str
    generated_at: datetime
    data_summary: Dict[str, Any]
    insights: List[HealthInsight]
    health_plan: Optional[HealthPlan]
    ai_analysis: str
    recommendations: List[Dict[str, Any]]
    risk_factors: List[str]
    confidence_score: float


# Note: HealthPlan model is now imported from api_models to maintain consistency
# This dataclass is kept for backward compatibility but should be migrated to use the API model


class AuraWellOrchestrator:
    """
    Core orchestration engine for AuraWell health management

    Coordinates between AI analysis, health data processing,
    and personalized recommendation generation.
    """

    def __init__(self, deepseek_client=None, apple_health_client=None):
        """
        Initialize the orchestrator

        Args:
            deepseek_client: Optional DeepSeek client instance
            apple_health_client: Optional AsyncAppleHealthClient instance
        """
        # Lazy import to avoid circular dependencies
        if deepseek_client is None:
            try:
                from .deepseek_client import DeepSeekClient

                self.deepseek_client = DeepSeekClient()
            except Exception as e:
                logger.warning(f"Failed to initialize DeepSeek client: {e}")
                self.deepseek_client = None
        else:
            self.deepseek_client = deepseek_client

        # Initialize Apple Health client
        if apple_health_client is None:
            try:
                from ..integrations.apple_health_client import AsyncAppleHealthClient
                self.apple_health_client = AsyncAppleHealthClient()
            except Exception as e:
                logger.warning(f"Failed to initialize Apple Health client: {e}")
                self.apple_health_client = None
        else:
            self.apple_health_client = apple_health_client

        self.insights_cache: Dict[str, List[HealthInsight]] = {}
        self.plans_cache: Dict[str, HealthPlan] = {}

        logger.info("AuraWell Orchestrator v2 initialized with Apple Health integration")

    async def analyze_user_comprehensive_health(
        self,
        user_id: str,
        days_back: int = 7,
        include_ai_analysis: bool = True,
        generate_health_plan: bool = True
    ) -> ComprehensiveHealthReport:
        """
        Perform comprehensive health analysis by fetching real data from Apple Health
        and generating AI-powered insights and recommendations.
        
        This is the main E2E method that connects all components:
        Data Fetching → Analysis → AI Insights → Health Plan → Final Report
        
        Args:
            user_id: User identifier
            days_back: Number of days to fetch historical data
            include_ai_analysis: Whether to include DeepSeek AI analysis
            generate_health_plan: Whether to generate a personalized health plan
            
        Returns:
            ComprehensiveHealthReport with all analysis results
        """
        logger.info(f"Starting comprehensive health analysis for user {user_id}")
        
        try:
            # Step 1: Fetch real health data from Apple Health
            health_data = await self._fetch_comprehensive_health_data(user_id, days_back)
            
            # Step 2: Analyze the data and generate insights
            insights = await self.analyze_user_health_data(
                user_profile=health_data["user_profile"],
                activity_data=health_data.get("activity_data", []),
                sleep_data=health_data.get("sleep_data", []),
                heart_rate_data=health_data.get("heart_rate_data", []),
                nutrition_data=health_data.get("nutrition_data", [])
            )
            
            # Step 3: Generate AI analysis if requested
            ai_analysis = ""
            if include_ai_analysis and self.deepseek_client:
                ai_analysis = await self._generate_comprehensive_ai_analysis(
                    health_data, insights
                )
            
            # Step 4: Extract recommendations and risk factors
            recommendations = self._extract_actionable_recommendations(insights)
            risk_factors = self._identify_risk_factors(health_data, insights)
            
            # Step 5: Generate personalized health plan if requested
            health_plan = None
            if generate_health_plan:
                user_preferences = health_data.get("user_preferences", {})
                health_plan = await self.create_personalized_health_plan(
                    user_profile=health_data["user_profile"],
                    user_preferences=user_preferences,
                    recent_insights=insights
                )
            
            # Step 6: Calculate overall confidence score
            confidence_score = self._calculate_confidence_score(health_data, insights)
            
            # Step 7: Create comprehensive report
            report = ComprehensiveHealthReport(
                user_id=user_id,
                generated_at=datetime.now(timezone.utc),
                data_summary=self._create_data_summary(health_data),
                insights=insights,
                health_plan=health_plan,
                ai_analysis=ai_analysis,
                recommendations=recommendations,
                risk_factors=risk_factors,
                confidence_score=confidence_score
            )
            
            logger.info(f"Comprehensive health analysis completed for user {user_id}")
            logger.info(f"Generated {len(insights)} insights, {len(recommendations)} recommendations")
            
            return report
            
        except Exception as e:
            logger.error(f"Failed to perform comprehensive health analysis: {e}")
            raise
    
    async def _fetch_comprehensive_health_data(
        self, user_id: str, days_back: int
    ) -> Dict[str, Any]:
        """
        Fetch comprehensive health data from Apple Health
        
        Args:
            user_id: User identifier
            days_back: Number of days to fetch historical data
            
        Returns:
            Dictionary containing all fetched health data
        """
        if not self.apple_health_client:
            raise ValueError("Apple Health client not available")
            
        # Calculate date range
        end_date = datetime.now().strftime('%Y-%m-%d')
        start_date = (datetime.now() - timedelta(days=days_back)).strftime('%Y-%m-%d')
        
        logger.info(f"Fetching health data from {start_date} to {end_date}")
        
        try:
            # Fetch all types of health data in parallel
            tasks = [
                self.apple_health_client.get_user_profile(user_id),
                self.apple_health_client.get_activity_data(user_id, start_date, end_date),
                self.apple_health_client.get_sleep_analysis(user_id, start_date, end_date),
                self.apple_health_client.get_health_samples(
                    user_id, "HKQuantityTypeIdentifierHeartRate", start_date, end_date
                ),
                self.apple_health_client.get_workouts(user_id, start_date, end_date),
                self.apple_health_client.get_health_summary(
                    user_id, start_date, end_date, include_workouts=True, include_sleep=True
                )
            ]
            
            # Execute all requests concurrently
            import asyncio
            results = await asyncio.gather(*tasks, return_exceptions=True)
            
            # Process results
            user_profile = results[0] if not isinstance(results[0], Exception) else {}
            activity_data = results[1] if not isinstance(results[1], Exception) else {}
            sleep_data = results[2] if not isinstance(results[2], Exception) else {}
            heart_rate_data = results[3] if not isinstance(results[3], Exception) else {}
            workouts = results[4] if not isinstance(results[4], Exception) else {}
            health_summary = results[5] if not isinstance(results[5], Exception) else {}
            
            # Transform data into the format expected by analysis methods
            formatted_data = {
                "user_profile": self._format_user_profile(user_profile),
                "activity_data": self._format_activity_data(activity_data),
                "sleep_data": self._format_sleep_data(sleep_data),
                "heart_rate_data": self._format_heart_rate_data(heart_rate_data),
                "nutrition_data": [],  # Will be populated when nutrition API is available
                "workouts": self._format_workouts(workouts),
                "health_summary": health_summary,
                "user_preferences": self._extract_user_preferences(user_profile)
            }
            
            logger.info("Successfully fetched and formatted comprehensive health data")
            return formatted_data
            
        except Exception as e:
            logger.error(f"Failed to fetch comprehensive health data: {e}")
            # Return minimal data structure to prevent total failure
            return {
                "user_profile": {"user_id": user_id, "age": "未知", "gender": "未知"},
                "activity_data": [],
                "sleep_data": [],
                "heart_rate_data": [],
                "nutrition_data": [],
                "workouts": [],
                "health_summary": {},
                "user_preferences": {}
            }

    async def _generate_comprehensive_ai_analysis(
        self, health_data: Dict[str, Any], insights: List[HealthInsight]
    ) -> str:
        """
        Generate comprehensive AI analysis using DeepSeek with real health data
        
        Args:
            health_data: Complete health data dictionary
            insights: Generated health insights
            
        Returns:
            Comprehensive AI analysis text
        """
        if not self.deepseek_client:
            return "AI分析暂不可用"
            
        try:
            # Prepare comprehensive context for AI
            context = {
                "user_profile": health_data["user_profile"],
                "data_summary": self._create_detailed_data_summary(health_data),
                "insights_summary": [
                    {
                        "type": insight.insight_type.value,
                        "priority": insight.priority.value,
                        "title": insight.title,
                        "description": insight.description
                    }
                    for insight in insights
                ],
                "health_metrics": self._extract_key_metrics(health_data)
            }
            
            # Create comprehensive AI prompt
            messages = [
                {
                    "role": "system",
                    "content": """你是AuraWell的高级健康分析专家。基于用户的真实健康数据，提供专业、个性化的健康分析报告。

请提供：
1. 整体健康状况评估
2. 关键健康指标分析
3. 潜在风险因素识别
4. 个性化改善建议
5. 长期健康目标建议

请用专业但易懂的语言，提供实用的健康指导。"""
                },
                {
                    "role": "user",
                    "content": f"""请对以下用户的健康数据进行综合分析：

用户档案：{context['user_profile']}

数据摘要：{context['data_summary']}

关键指标：{context['health_metrics']}

已识别洞察：{context['insights_summary']}

请提供详细的健康分析报告。"""
                }
            ]
            
            # Get comprehensive AI response
            response = await self.deepseek_client.get_deepseek_response(
                messages=messages,
                model="deepseek-reasoner",
                temperature=0.3,
                max_tokens=2000
            )
            
            logger.info("Generated comprehensive AI analysis")
            return response.content
            
        except Exception as e:
            logger.error(f"Failed to generate AI analysis: {e}")
            return f"AI分析过程中出现错误：{str(e)}"

    def _format_user_profile(self, profile_data: Dict[str, Any]) -> Dict[str, Any]:
        """Format user profile data for analysis"""
        return {
            "user_id": profile_data.get("user_id", "unknown"),
            "age": profile_data.get("age", "未知"),
            "gender": profile_data.get("gender", "未知"),
            "height": profile_data.get("height", 0),
            "weight": profile_data.get("weight", 0),
            "bmi": profile_data.get("bmi", 0),
            "daily_steps_goal": profile_data.get("daily_steps_goal", 10000),
            "sleep_duration_goal_hours": profile_data.get("sleep_duration_goal_hours", 8.0)
        }

    def _format_activity_data(self, activity_data: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Format activity data for analysis"""
        if not activity_data or "samples" not in activity_data:
            return []
        
        formatted = []
        for sample in activity_data.get("samples", []):
            formatted.append({
                "date": sample.get("date", ""),
                "steps": sample.get("value", 0),
                "distance": sample.get("distance", 0),
                "calories": sample.get("calories_burned", 0),
                "active_minutes": sample.get("active_minutes", 0)
            })
        
        return formatted

    def _format_sleep_data(self, sleep_data: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Format sleep data for analysis"""
        if not sleep_data or "sessions" not in sleep_data:
            return []
        
        formatted = []
        for session in sleep_data.get("sessions", []):
            formatted.append({
                "date": session.get("date", ""),
                "duration_hours": session.get("duration_hours", 0),
                "efficiency": session.get("efficiency", 0),
                "deep_sleep_minutes": session.get("deep_sleep_minutes", 0),
                "rem_sleep_minutes": session.get("rem_sleep_minutes", 0),
                "wake_ups": session.get("wake_ups", 0)
            })
        
        return formatted

    def _format_heart_rate_data(self, hr_data: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Format heart rate data for analysis"""
        if not hr_data or "samples" not in hr_data:
            return []
        
        formatted = []
        for sample in hr_data.get("samples", []):
            formatted.append({
                "timestamp": sample.get("timestamp", ""),
                "value": sample.get("value", 0),
                "context": sample.get("context", "resting")
            })
        
        return formatted

    def _format_workouts(self, workouts_data: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Format workouts data for analysis"""
        if not workouts_data or "workouts" not in workouts_data:
            return []
        
        return workouts_data.get("workouts", [])

    def _extract_user_preferences(self, profile_data: Dict[str, Any]) -> Dict[str, Any]:
        """Extract user preferences from profile data"""
        return {
            "fitness_goals": profile_data.get("fitness_goals", []),
            "dietary_preferences": profile_data.get("dietary_preferences", []),
            "exercise_preferences": profile_data.get("exercise_preferences", []),
            "health_concerns": profile_data.get("health_concerns", [])
        }

    def _create_data_summary(self, health_data: Dict[str, Any]) -> Dict[str, Any]:
        """Create a summary of the health data for the report"""
        return {
            "data_sources": ["Apple Health"],
            "data_types_collected": [
                key for key in health_data.keys() 
                if health_data[key] and key != "user_profile"
            ],
            "date_range": self._get_data_date_range(health_data),
            "total_data_points": self._count_total_data_points(health_data)
        }

    def _create_detailed_data_summary(self, health_data: Dict[str, Any]) -> str:
        """Create detailed data summary for AI analysis"""
        summary_parts = []
        
        # Activity summary
        activity_data = health_data.get("activity_data", [])
        if activity_data:
            avg_steps = sum(data.get("steps", 0) for data in activity_data) / len(activity_data)
            summary_parts.append(f"最近{len(activity_data)}天平均步数: {int(avg_steps)}步")
        
        # Sleep summary
        sleep_data = health_data.get("sleep_data", [])
        if sleep_data:
            avg_sleep = sum(data.get("duration_hours", 0) for data in sleep_data) / len(sleep_data)
            summary_parts.append(f"最近{len(sleep_data)}天平均睡眠: {avg_sleep:.1f}小时")
        
        # Heart rate summary
        hr_data = health_data.get("heart_rate_data", [])
        if hr_data:
            avg_hr = sum(data.get("value", 0) for data in hr_data) / len(hr_data)
            summary_parts.append(f"平均心率: {int(avg_hr)}次/分")
        
        return "; ".join(summary_parts) if summary_parts else "数据收集中"

    def _extract_key_metrics(self, health_data: Dict[str, Any]) -> Dict[str, Any]:
        """Extract key health metrics for AI analysis"""
        metrics = {}
        
        # Calculate key metrics from the data
        activity_data = health_data.get("activity_data", [])
        if activity_data:
            metrics["avg_daily_steps"] = sum(d.get("steps", 0) for d in activity_data) / len(activity_data)
            metrics["avg_daily_calories"] = sum(d.get("calories", 0) for d in activity_data) / len(activity_data)
        
        sleep_data = health_data.get("sleep_data", [])
        if sleep_data:
            metrics["avg_sleep_duration"] = sum(d.get("duration_hours", 0) for d in sleep_data) / len(sleep_data)
            metrics["avg_sleep_efficiency"] = sum(d.get("efficiency", 0) for d in sleep_data) / len(sleep_data)
        
        return metrics

    def _extract_actionable_recommendations(self, insights: List[HealthInsight]) -> List[Dict[str, Any]]:
        """Extract actionable recommendations from insights"""
        recommendations = []
        
        for insight in insights:
            for rec in insight.recommendations:
                recommendations.append({
                    "category": insight.insight_type.value,
                    "priority": insight.priority.value,
                    "action": rec,
                    "confidence": insight.confidence_score
                })
        
        return recommendations

    def _identify_risk_factors(self, health_data: Dict[str, Any], insights: List[HealthInsight]) -> List[str]:
        """Identify potential health risk factors"""
        risk_factors = []
        
        # Check for activity-related risks
        activity_data = health_data.get("activity_data", [])
        if activity_data:
            avg_steps = sum(d.get("steps", 0) for d in activity_data) / len(activity_data)
            if avg_steps < 5000:
                risk_factors.append("日常活动量不足")
        
        # Check for sleep-related risks
        sleep_data = health_data.get("sleep_data", [])
        if sleep_data:
            avg_sleep = sum(d.get("duration_hours", 0) for d in sleep_data) / len(sleep_data)
            if avg_sleep < 6:
                risk_factors.append("睡眠不足")
            elif avg_sleep > 9:
                risk_factors.append("睡眠过多")
        
        return risk_factors

    def _calculate_confidence_score(self, health_data: Dict[str, Any], insights: List[HealthInsight]) -> float:
        """Calculate overall confidence score for the analysis"""
        scores = []
        
        # Data completeness score
        data_types = ["activity_data", "sleep_data", "heart_rate_data"]
        completeness = sum(1 for dt in data_types if health_data.get(dt)) / len(data_types)
        scores.append(completeness)
        
        # Insights confidence scores
        if insights:
            avg_insight_confidence = sum(i.confidence_score for i in insights) / len(insights)
            scores.append(avg_insight_confidence)
        
        return sum(scores) / len(scores) if scores else 0.5

    def _get_data_date_range(self, health_data: Dict[str, Any]) -> Dict[str, str]:
        """Get the date range of the collected data"""
        # This is a simplified implementation
        return {
            "start_date": "7天前",
            "end_date": "今天"
        }

    def _count_total_data_points(self, health_data: Dict[str, Any]) -> int:
        """Count total data points collected"""
        count = 0
        for key, value in health_data.items():
            if isinstance(value, list):
                count += len(value)
        return count

    async def analyze_user_health_data(
        self,
        user_profile: Dict[str, Any],
        activity_data: List[Dict[str, Any]] = None,
        sleep_data: List[Dict[str, Any]] = None,
        heart_rate_data: List[Dict[str, Any]] = None,
        nutrition_data: List[Dict[str, Any]] = None,
    ) -> List[HealthInsight]:
        """
        Analyze comprehensive user health data and generate insights

        Args:
            user_profile: User profile information as dict
            activity_data: Recent activity summaries as list of dicts
            sleep_data: Recent sleep sessions as list of dicts
            heart_rate_data: Recent heart rate measurements as list of dicts
            nutrition_data: Recent nutrition entries as list of dicts

        Returns:
            List of generated health insights
        """
        user_id = user_profile.get("user_id", "unknown")
        logger.info(f"Analyzing health data for user {user_id}")

        insights = []

        # Generate different types of insights
        if activity_data:
            insights.extend(
                self._analyze_activity_patterns(user_profile, activity_data)
            )
        if sleep_data:
            insights.extend(self._analyze_sleep_quality(user_profile, sleep_data))
        if nutrition_data:
            insights.extend(
                self._analyze_nutrition_balance(user_profile, nutrition_data)
            )
        if activity_data or sleep_data:
            insights.extend(
                self._analyze_goal_progress(
                    user_profile, activity_data or [], sleep_data or []
                )
            )

        # Generate AI insights if client is available
        if self.deepseek_client:
            ai_insights = await self._generate_ai_insights(
                user_profile, activity_data, sleep_data, nutrition_data
            )
            insights.extend(ai_insights)

        # Cache insights
        self.insights_cache[user_id] = insights

        logger.info(f"Generated {len(insights)} insights for user {user_id}")
        return insights

    async def create_personalized_health_plan(
        self,
        user_profile: Dict[str, Any],
        user_preferences: Dict[str, Any] = None,
        recent_insights: List[HealthInsight] = None,
    ) -> HealthPlan:
        """
        Create a personalized health plan based on user data and insights

        Args:
            user_profile: User profile information as dict
            user_preferences: User preferences and goals as dict
            recent_insights: Recent health insights

        Returns:
            Personalized health plan
        """
        user_id = user_profile.get("user_id", "unknown")
        logger.info(f"Creating health plan for user {user_id}")

        plan_id = f"plan_{user_id}_{int(datetime.now().timestamp())}"

        # Generate AI-powered health plan if client is available
        if self.deepseek_client and user_preferences and recent_insights:
            plan_content = await self._generate_ai_health_plan(
                user_profile, user_preferences, recent_insights
            )
        else:
            plan_content = self._get_default_health_plan(user_profile)

        # Create modules from plan content
        modules = []
        if "modules" in plan_content:
            for module_data in plan_content["modules"]:
                try:
                    module = HealthPlanModule(
                        module_type=module_data.get("type", "general"),
                        title=module_data.get("title", "健康模块"),
                        description=module_data.get("description", ""),
                        content=module_data.get("content", {}),
                        duration_days=plan_content.get("duration_days", 30),
                    )
                    modules.append(module)
                except Exception as e:
                    logger.warning(f"Failed to create module: {e}")
                    # Fallback to dict format for compatibility
                    modules.append(module_data)

        health_plan = HealthPlan(
            plan_id=plan_id,
            title=plan_content.get("title", "个性化健康计划"),
            description=plan_content.get(
                "description", "基于您的健康数据和目标制定的个性化计划"
            ),
            modules=modules,
            duration_days=plan_content.get("duration_days", 30),
            status="active",
            progress=0.0,
            created_at=datetime.now(timezone.utc),
            updated_at=datetime.now(timezone.utc),
        )

        # Cache the plan
        self.plans_cache[user_id] = health_plan

        logger.info(f"Created health plan {plan_id} for user {user_id}")
        return health_plan

    def get_daily_recommendations(
        self, user_id: str, target_date: Optional[datetime] = None
    ) -> List[Dict[str, Any]]:
        """
        Get daily recommendations for a user

        Args:
            user_id: User identifier
            target_date: Target date for recommendations (default: today)

        Returns:
            List of daily recommendations
        """
        if target_date is None:
            target_date = datetime.now(timezone.utc)

        logger.info(f"Getting daily recommendations for user {user_id}")

        # Get cached plan if available
        if user_id in self.plans_cache:
            plan = self.plans_cache[user_id]
            if plan.valid_until > datetime.now(timezone.utc):
                return plan.daily_recommendations

        # Generate new recommendations if no valid plan exists
        return self._generate_daily_recommendations(user_id, target_date)

    def get_system_status(self) -> Dict[str, Any]:
        """Get system status information"""
        return {
            "cached_users": len(self.insights_cache),
            "cached_plans": len(self.plans_cache),
            "deepseek_client_status": (
                "connected" if self.deepseek_client else "disconnected"
            ),
            "last_updated": datetime.now(timezone.utc).isoformat(),
        }

    def _analyze_activity_patterns(
        self, user_profile: Dict[str, Any], activity_data: List[Dict[str, Any]]
    ) -> List[HealthInsight]:
        """Analyze activity patterns and generate insights"""
        insights = []

        if not activity_data:
            return insights

        # Calculate average daily steps
        total_steps = sum(data.get("steps", 0) for data in activity_data)
        avg_steps = total_steps / len(activity_data)

        # Check against user's goal
        steps_goal = user_profile.get("daily_steps_goal", 10000)
        goal_achievement = (avg_steps / steps_goal) * 100

        if goal_achievement < 70:
            insights.append(
                HealthInsight(
                    insight_id=f"activity_low_{user_profile.get('user_id')}_{int(datetime.now().timestamp())}",
                    insight_type=InsightType.ACTIVITY_PATTERN,
                    priority=InsightPriority.MEDIUM,
                    title="步数目标完成度较低",
                    description=f"最近平均每日步数为 {int(avg_steps)} 步，仅达到目标的 {goal_achievement:.1f}%",
                    recommendations=[
                        "尝试在日常生活中增加更多步行机会",
                        "设置每小时提醒，进行短暂的步行",
                        "选择楼梯而不是电梯",
                    ],
                    data_points={
                        "avg_steps": avg_steps,
                        "goal_steps": steps_goal,
                        "achievement_percentage": goal_achievement,
                    },
                    confidence_score=0.9,
                    generated_at=datetime.now(timezone.utc),
                )
            )
        elif goal_achievement > 120:
            insights.append(
                HealthInsight(
                    insight_id=f"activity_high_{user_profile.get('user_id')}_{int(datetime.now().timestamp())}",
                    insight_type=InsightType.ACTIVITY_PATTERN,
                    priority=InsightPriority.LOW,
                    title="步数目标超额完成",
                    description=f"最近平均每日步数为 {int(avg_steps)} 步，超出目标 {goal_achievement-100:.1f}%",
                    recommendations=[
                        "保持当前的活动水平",
                        "考虑设置更高的步数目标",
                        "注意适当休息，避免过度运动",
                    ],
                    data_points={
                        "avg_steps": avg_steps,
                        "goal_steps": steps_goal,
                        "achievement_percentage": goal_achievement,
                    },
                    confidence_score=0.9,
                    generated_at=datetime.now(timezone.utc),
                )
            )

        return insights

    def _analyze_sleep_quality(
        self, user_profile: Dict[str, Any], sleep_data: List[Dict[str, Any]]
    ) -> List[HealthInsight]:
        """Analyze sleep quality and generate insights"""
        insights = []

        if not sleep_data:
            return insights

        # Calculate average sleep duration
        total_duration = sum(data.get("duration_hours", 0) for data in sleep_data)
        avg_duration = total_duration / len(sleep_data)

        sleep_goal = user_profile.get("sleep_duration_goal_hours", 8.0)

        if avg_duration < 6.5:
            insights.append(
                HealthInsight(
                    insight_id=f"sleep_short_{user_profile.get('user_id')}_{int(datetime.now().timestamp())}",
                    insight_type=InsightType.SLEEP_QUALITY,
                    priority=InsightPriority.HIGH,
                    title="睡眠时间不足",
                    description=f"最近平均睡眠时间为 {avg_duration:.1f} 小时，低于推荐的 7-9 小时",
                    recommendations=[
                        "建立规律的睡眠时间表",
                        "睡前1小时避免使用电子设备",
                        "创造舒适的睡眠环境",
                    ],
                    data_points={
                        "avg_sleep_hours": avg_duration,
                        "goal_sleep_hours": sleep_goal,
                        "sleep_deficit": sleep_goal - avg_duration,
                    },
                    confidence_score=0.95,
                    generated_at=datetime.now(timezone.utc),
                )
            )

        return insights

    def _analyze_nutrition_balance(
        self, user_profile: Dict[str, Any], nutrition_data: List[Dict[str, Any]]
    ) -> List[HealthInsight]:
        """Analyze nutrition balance and generate insights"""
        insights = []

        if not nutrition_data:
            return insights

        # Calculate average daily calories
        total_calories = sum(data.get("calories", 0) for data in nutrition_data)
        avg_calories = total_calories / len(nutrition_data)

        # Simple calorie recommendation (in production, would use proper BMR/TDEE calculation)
        estimated_needs = 2000  # Simplified
        calorie_ratio = avg_calories / estimated_needs

        if calorie_ratio < 0.8:
            insights.append(
                HealthInsight(
                    insight_id=f"nutrition_low_{user_profile.get('user_id')}_{int(datetime.now().timestamp())}",
                    insight_type=InsightType.NUTRITION_BALANCE,
                    priority=InsightPriority.MEDIUM,
                    title="卡路里摄入不足",
                    description=f"平均每日摄入 {int(avg_calories)} 卡路里，低于建议的 {int(estimated_needs)} 卡路里",
                    recommendations=[
                        "增加健康的高热量食物",
                        "确保三餐规律",
                        "添加健康的零食",
                    ],
                    data_points={
                        "avg_calories": avg_calories,
                        "recommended_calories": estimated_needs,
                        "calorie_deficit": estimated_needs - avg_calories,
                    },
                    confidence_score=0.85,
                    generated_at=datetime.now(timezone.utc),
                )
            )
        elif calorie_ratio > 1.2:
            insights.append(
                HealthInsight(
                    insight_id=f"nutrition_high_{user_profile.get('user_id')}_{int(datetime.now().timestamp())}",
                    insight_type=InsightType.NUTRITION_BALANCE,
                    priority=InsightPriority.MEDIUM,
                    title="卡路里摄入过多",
                    description=f"平均每日摄入 {int(avg_calories)} 卡路里，高于建议的 {int(estimated_needs)} 卡路里",
                    recommendations=[
                        "控制食物分量",
                        "选择低热量高营养的食物",
                        "增加运动量",
                    ],
                    data_points={
                        "avg_calories": avg_calories,
                        "recommended_calories": estimated_needs,
                        "calorie_excess": avg_calories - estimated_needs,
                    },
                    confidence_score=0.85,
                    generated_at=datetime.now(timezone.utc),
                )
            )

        return insights

    def _analyze_goal_progress(
        self,
        user_profile: Dict[str, Any],
        activity_data: List[Dict[str, Any]],
        sleep_data: List[Dict[str, Any]],
    ) -> List[HealthInsight]:
        """Analyze progress towards health goals"""
        insights = []

        # Analyze overall goal progress
        progress_score = 0
        total_goals = 0

        # Steps goal progress
        if activity_data and user_profile.get("daily_steps_goal"):
            avg_steps = sum(data.get("steps", 0) for data in activity_data) / len(
                activity_data
            )
            steps_progress = min(avg_steps / user_profile["daily_steps_goal"], 1.0)
            progress_score += steps_progress
            total_goals += 1

        # Sleep goal progress
        if sleep_data and user_profile.get("sleep_duration_goal_hours"):
            avg_sleep = sum(data.get("duration_hours", 0) for data in sleep_data) / len(
                sleep_data
            )
            sleep_progress = min(
                avg_sleep / user_profile["sleep_duration_goal_hours"], 1.0
            )
            progress_score += sleep_progress
            total_goals += 1

        if total_goals > 0:
            overall_progress = (progress_score / total_goals) * 100

            insights.append(
                HealthInsight(
                    insight_id=f"goal_progress_{user_profile.get('user_id')}_{int(datetime.now().timestamp())}",
                    insight_type=InsightType.GOAL_PROGRESS,
                    priority=InsightPriority.LOW,
                    title=f"整体目标完成度: {overall_progress:.1f}%",
                    description=f"您的健康目标整体完成度为 {overall_progress:.1f}%",
                    recommendations=[
                        "继续保持良好的健康习惯",
                        "关注完成度较低的目标",
                        "适当调整目标以保持挑战性",
                    ],
                    data_points={
                        "overall_progress": overall_progress,
                        "goals_tracked": total_goals,
                    },
                    confidence_score=0.9,
                    generated_at=datetime.now(timezone.utc),
                )
            )

        return insights

    async def _generate_ai_insights(
        self,
        user_profile: Dict[str, Any],
        activity_data: List[Dict[str, Any]],
        sleep_data: List[Dict[str, Any]],
        nutrition_data: List[Dict[str, Any]],
    ) -> List[HealthInsight]:
        """Generate AI-powered insights using DeepSeek"""
        insights = []

        try:
            # Prepare data summary for AI analysis
            data_summary = self._prepare_data_summary(
                user_profile, activity_data, sleep_data, nutrition_data
            )

            # Create AI prompt
            messages = [
                {
                    "role": "system",
                    "content": "你是AuraWell的健康分析专家。基于用户的健康数据，提供专业的健康洞察和建议。",
                },
                {
                    "role": "user",
                    "content": f"请分析以下健康数据并提供洞察：\n{data_summary}",
                },
            ]

            # Get AI response
            response = await self.deepseek_client.get_deepseek_response(
                messages=messages, model="deepseek-reasoner", temperature=0.3
            )

            # Parse AI insights (simplified)
            ai_insight = HealthInsight(
                insight_id=f"ai_insight_{user_profile.get('user_id')}_{int(datetime.now().timestamp())}",
                insight_type=InsightType.RECOMMENDATION,
                priority=InsightPriority.MEDIUM,
                title="AI健康分析",
                description=(
                    response.content[:200] + "..."
                    if len(response.content) > 200
                    else response.content
                ),
                recommendations=["基于AI分析的个性化建议"],
                data_points={"ai_analysis": response.content},
                confidence_score=0.8,
                generated_at=datetime.now(timezone.utc),
            )

            insights.append(ai_insight)

        except Exception as e:
            logger.error(f"Failed to generate AI insights: {e}")

        return insights

    async def _generate_ai_health_plan(
        self,
        user_profile: Dict[str, Any],
        user_preferences: Dict[str, Any],
        recent_insights: List[HealthInsight],
    ) -> Dict[str, Any]:
        """Generate AI-powered health plan"""
        try:
            # Prepare context for AI
            context = {
                "user_profile": user_profile,
                "preferences": user_preferences,
                "recent_insights": [
                    {
                        "type": insight.insight_type.value,
                        "priority": insight.priority.value,
                        "title": insight.title,
                    }
                    for insight in recent_insights[:5]  # Top 5 insights
                ],
            }

            messages = [
                {
                    "role": "system",
                    "content": "你是AuraWell的健康计划专家。基于用户信息和健康洞察，制定个性化的30天健康计划。",
                },
                {"role": "user", "content": f"请为以下用户制定健康计划：\n{context}"},
            ]

            response = await self.deepseek_client.get_deepseek_response(
                messages=messages, model="deepseek-reasoner", temperature=0.5
            )

            # Return structured plan (simplified)
            return {
                "title": "AI个性化健康计划",
                "description": response.content,
                "goals": [
                    {
                        "type": "daily_steps",
                        "target": user_profile.get("daily_steps_goal", 10000),
                    },
                    {
                        "type": "sleep_hours",
                        "target": user_profile.get("sleep_duration_goal_hours", 8.0),
                    },
                ],
                "daily_recommendations": [
                    {
                        "time": "morning",
                        "title": "晨间运动",
                        "activity": "晨间运动",
                        "duration": 30,
                    },
                    {
                        "time": "evening",
                        "title": "放松活动",
                        "activity": "放松活动",
                        "duration": 15,
                    },
                ],
                "weekly_targets": {"exercise_sessions": 3, "meditation_sessions": 5},
            }

        except Exception as e:
            logger.error(f"Failed to generate AI health plan: {e}")
            return self._get_default_health_plan(user_profile)

    def _prepare_data_summary(
        self,
        user_profile: Dict[str, Any],
        activity_data: List[Dict[str, Any]],
        sleep_data: List[Dict[str, Any]],
        nutrition_data: List[Dict[str, Any]],
    ) -> str:
        """Prepare a summary of health data for AI analysis"""
        summary_parts = []

        # User profile summary
        age = user_profile.get("age", "未知")
        gender = user_profile.get("gender", "未知")
        summary_parts.append(f"用户信息: {age}岁, {gender}")

        # Activity summary
        if activity_data:
            avg_steps = sum(data.get("steps", 0) for data in activity_data) / len(
                activity_data
            )
            summary_parts.append(
                f"活动数据: 最近{len(activity_data)}天平均步数{int(avg_steps)}步"
            )

        # Sleep summary
        if sleep_data:
            avg_sleep = sum(data.get("duration_hours", 0) for data in sleep_data) / len(
                sleep_data
            )
            summary_parts.append(
                f"睡眠数据: 最近{len(sleep_data)}天平均睡眠{avg_sleep:.1f}小时"
            )

        # Nutrition summary
        if nutrition_data:
            avg_calories = sum(
                data.get("calories", 0) for data in nutrition_data
            ) / len(nutrition_data)
            summary_parts.append(
                f"营养数据: 最近{len(nutrition_data)}天平均摄入{int(avg_calories)}卡路里"
            )

        return "; ".join(summary_parts)

    def _generate_daily_recommendations(
        self, user_id: str, target_date: datetime
    ) -> List[Dict[str, Any]]:
        """Generate daily recommendations for a user"""
        # Default recommendations (in production, this would be more sophisticated)
        return [
            {
                "time": "morning",
                "type": "exercise",
                "title": "晨间步行",
                "description": "进行20-30分钟的轻松步行",
                "duration_minutes": 25,
                "priority": "medium",
            },
            {
                "time": "afternoon",
                "type": "hydration",
                "title": "补充水分",
                "description": "确保已饮用足够的水",
                "priority": "high",
            },
            {
                "time": "evening",
                "type": "relaxation",
                "title": "放松活动",
                "description": "进行冥想或深呼吸练习",
                "duration_minutes": 10,
                "priority": "low",
            },
        ]

    def _get_default_health_plan(self, user_profile: Dict[str, Any]) -> Dict[str, Any]:
        """Get default health plan when AI generation fails"""
        return {
            "title": "基础健康计划",
            "description": "基于您的基本信息制定的健康计划",
            "duration_days": 30,
            "modules": [
                {
                    "type": "exercise",
                    "title": "基础运动计划",
                    "description": "适合初学者的运动方案",
                    "content": {
                        "daily_steps_goal": user_profile.get("daily_steps_goal", 10000),
                        "weekly_sessions": 3,
                        "session_duration": 30,
                    },
                },
                {
                    "type": "sleep",
                    "title": "睡眠管理计划",
                    "description": "改善睡眠质量的建议",
                    "content": {
                        "target_hours": user_profile.get(
                            "sleep_duration_goal_hours", 8.0
                        ),
                        "bedtime_routine": ["避免电子设备", "放松活动", "规律作息"],
                    },
                },
            ],
            "goals": [
                {
                    "type": "daily_steps",
                    "target": user_profile.get("daily_steps_goal", 10000),
                },
                {
                    "type": "sleep_hours",
                    "target": user_profile.get("sleep_duration_goal_hours", 8.0),
                },
            ],
            "daily_recommendations": [
                {
                    "time": "morning",
                    "title": "轻度运动",
                    "activity": "轻度运动",
                    "duration": 30,
                },
                {
                    "time": "evening",
                    "title": "放松时间",
                    "activity": "放松时间",
                    "duration": 15,
                },
            ],
            "weekly_targets": {"exercise_sessions": 3, "rest_days": 1},
        }

    def get_user_insights(self, user_id: str) -> List[HealthInsight]:
        """Get cached insights for a user"""
        return self.insights_cache.get(user_id, [])

    def get_user_health_plan(self, user_id: str) -> Optional[HealthPlan]:
        """Get cached health plan for a user"""
        return self.plans_cache.get(user_id)

    def clear_user_cache(self, user_id: str) -> None:
        """Clear cached data for a user"""
        self.insights_cache.pop(user_id, None)
        self.plans_cache.pop(user_id, None)
        logger.info(f"Cleared cache for user {user_id}")
